@startuml Diagrama de Transición de Estados - Solicitud de Vecino
[*] -> Creada : crear()
Creada --> RecibidaEnAdministración : [destinatario == administrador] \n recibirEnAdministración()
Creada --> RecibidaEnProveedor : [destinatario == proveedor] \n recibirEnProveedor()
RecibidaEnAdministración --> EnEvaluacion : evaluar()
EnEvaluacion --> Aceptada : aceptar()
EnEvaluacion --> Rechazada : rechazar()
RecibidaEnProveedor --> Aceptada : aceptar()
RecibidaEnProveedor --> Rechazada : rechazar()
Aceptada --> Solucionada : registrarSolucion()
Aceptada -> EnEspera : registrarEnEspera()
EnEspera --> Rechazada : rechazar()
EnEspera --> Solucionada : registrarSolucion()
Solucionada --> [*]
Rechazada --> [*]
@enduml